{
 "title": "Spritpreise",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Kraftstoff", "query": "e5, e10, diesel" }
  ]
 },
 "panels": [
  { "title": "Aktuell", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Günstigste Tankstelle im Umkreis",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "tankerkoenig.0.stations.cheapest.$Kraftstoff.name",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.cheapest.$Kraftstoff.name\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "tankerkoenig.0.stations.cheapest.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Günstigster Preis (Woche)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.cheapest.$Kraftstoff.feed",
     "query": "SELECT mode(\"value\") FROM \"tankerkoenig.0.stations.cheapest.$Kraftstoff.feed\" WHERE (\"value\" > 0) AND $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Teuerster Preis (Woche)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Markant",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.0.$Kraftstoff.feed",
     "query": "SELECT max(\"value\") FROM \"tankerkoenig.0.stations.0.$Kraftstoff.feed\" WHERE $timeFilter GROUP BY time(7d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.1.$Kraftstoff.feed",
     "query": "SELECT max(\"value\") FROM \"tankerkoenig.0.stations.1.$Kraftstoff.feed\" WHERE $timeFilter GROUP BY time(7d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Esso",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.2.$Kraftstoff.feed",
     "query": "SELECT max(\"value\") FROM \"tankerkoenig.0.stations.2.$Kraftstoff.feed\" WHERE $timeFilter GROUP BY time(7d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.3.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.4.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.5.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Preis pro Tankfüllung (45 Liter)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.cheapest.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.0.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Preis pro Tankfüllung (45 Liter)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Markant",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.0.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.0.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.1.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.1.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Esso",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.2.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.3.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.4.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.5.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.0.name",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.1.name",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.2.name",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.3.name",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.4.name",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.5.name",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.0.status",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.1.status",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.2.status",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.3.status",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.4.status",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Markant",
     "measurement": "tankerkoenig.0.stations.5.status",
     "query": "SELECT * FROM \"tankerkoenig.0.stations.0.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Markant",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.0.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.0.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.1.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.1.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Esso",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.2.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.3.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.4.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.5.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Preis pro Tankfüllung (45 Liter)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Markant",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.0.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.0.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.1.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.1.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Esso",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.2.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.3.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.4.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.5.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "*45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  { "title": "Historie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Historie",
   "type": "graph",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "alias": "Markant",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.0.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.0.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.1.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.1.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Esso",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.2.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral (Schortens)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.3.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral (WHV - Ebkerige)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.4.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral (WHV - Gökerstr.)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.5.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Preisveränderung",
   "type": "stat",
   "description": "Aussagekräftige bei einem Zeitraum >2 Tage",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Markant",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.0.$Kraftstoff.feed",
     "query": "SELECT max(\"value\") FROM \"tankerkoenig.0.stations.0.$Kraftstoff.feed\" WHERE (\"value\" > 0) AND $timeFilter GROUP BY time(12h) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.1.$Kraftstoff.feed",
     "query": "SELECT mean(\"value\") FROM \"tankerkoenig.0.stations.1.$Kraftstoff.short\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Esso",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.2.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral (Jever)",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.3.$Kraftstoff.feed",
     "query": "SELECT max(\"value\") FROM \"tankerkoenig.0.stations.3.$Kraftstoff.feed\" WHERE (\"value\" > 0) AND $timeFilter GROUP BY time(12h) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral (WHV - Ebkerige)",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.4.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Aral (WHV - Gökerstr.)",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tankerkoenig.0.stations.5.$Kraftstoff.feed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  }
 ]
}